# Fundamentals of Python

# Creating some lists

### A list is a data structure in Python that is a mutable, or changeable, ordered sequence of elements. Each element or value that is inside of a list is called an item.

In [2]:
List = [5,4,7,1,3,98,4]

In [3]:
List

[5, 4, 7, 1, 3, 98, 4]

In [4]:
type(List)

list

In [5]:
List2 = ['Hello', True, None, 14.5, 9]

In [6]:
List2

['Hello', True, None, 14.5, 9]

In [7]:
type(List2)

list

In [9]:
List3 = [List, List2]

In [10]:
List3

[[5, 4, 7, 1, 3, 98, 4], ['Hello', True, None, 14.5, 9]]

In [11]:
range(10)

range(0, 10)

In [12]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
list(range(10,2))

[]

In [14]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

# Using the [ ] Brackets

In [15]:
w = ['a','b','c','d','e']

In [16]:
w[0]

'a'

In [18]:
len(w)

5

In [19]:
w[-1]

'e'

In [20]:
w[2] = 'Changed'

In [21]:
w

['a', 'b', 'Changed', 'd', 'e']

In [22]:
w

['a', 'b', 'Changed', 'd', 'e']

In [23]:
w[0] = 100

In [24]:
w

[100, 'b', 'Changed', 'd', 'e']

# Slicing

### Indices in python start at 0, therefore, the first element of the list was index 0 (not 1). ###The last element of list has the index -1, therefore working backwards, the indices ###take values -1, -2, -3 ... till the first element.

In [10]:
letters = ['A','B','C','D','E','F','G','H','I','J']

In [11]:
letters

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [12]:
letters[0]

'A'

In [13]:
letters[-10]

'A'

In [27]:
letters[1:2]

['B']

In [28]:
letters[1:5:2]

['B', 'D']

In [29]:
letters[2:]

['C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [30]:
letters[:3]

['A', 'B', 'C']

In [35]:
letters[-3:]

['H', 'I', 'J']

In [37]:
len(letters)

10

In [41]:
letters[-10:]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

# Tuples in Python

### A tuple is an immutable sequence of Python objects. Tuples are sequences, just like lists. The differences between tuples and lists are, the tuples cannot be changed unlike lists and tuples use parentheses, whereas lists use square brackets.

In [42]:
t1 = (1,2,3,4,5)

In [44]:
t1[1]

2

In [45]:
# As we see below, we are unable to assign the second item in the tuple to a new value
t1[1] = 99

TypeError: 'tuple' object does not support item assignment

In [46]:
t2 = ('hello', 14.5,7)

In [47]:
type(t2)

tuple

# Functions in Python

In [48]:
range(20,31)

range(20, 31)

In [49]:
list(range(20,31))

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [51]:
list1 = list(range(20,31))

In [52]:
list1

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [53]:
type(list1)

list

In [54]:
len(list1)

11

In [55]:
max(list1)

30

In [56]:
min(list1)

20

In [57]:
max(1,50,4,100)

100

# Numpy and Arrays in Python

In [58]:
l = [23,43,-90,8989,456]

In [59]:
l

[23, 43, -90, 8989, 456]

In [61]:
import numpy as np

In [63]:
a = np.array(l)

In [64]:
a

array([  23,   43,  -90, 8989,  456])

In [70]:
list2 = [1,4.5,'Hello']

In [71]:
b = np.array(list2)

In [72]:
b

array(['1', '4.5', 'Hello'], dtype='<U32')

In [74]:
print(b)

['1' '4.5' 'Hello']


In [75]:
a.mean()

1884.2

In [77]:
a

array([  23,   43,  -90, 8989,  456])

In [78]:
b = a[1:3]

In [79]:
b

array([ 43, -90])

In [80]:
b[1] = 80000000

In [82]:
b

array([      43, 80000000])

In [83]:
a

array([      23,       43, 80000000,     8989,      456])

# Homework: Financial Statement Analysis

### With the data provided below, calculate the following financial metrics:
### . Profit for each month
### . Profit after tax for each month (tax rate is 30%)
### . Profit margin for each month (as %) - equals to profit after tax divided by revenue
### . Good months - where the profit after tax was greater than the mean for the year
### . Bad months - where the profit after tax was less than the mean for the year
### . The best month - where the profit after tax was the maximum for the year
### . The worst month - where the profit after tax was the minimum for the year

In [2]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [4]:
len(revenue)

12

In [5]:
len(expenses)

12

In [6]:
# Profit for each month
profit = [0,0,0,0,0,0,0,0,0,0,0,0]
for i in range(0,12):
    profit[i] = revenue[i] - expenses[i]
    

In [7]:
print(profit)

[2522.67, 1911.3900000000003, -3707.790000000001, -2914.3099999999995, -599.9200000000001, 7265.24, 8210.550000000001, 3944.9700000000003, 3328.3899999999994, -2238.6500000000015, 659.5999999999985, 11629.54]


In [172]:
type(profit)

list

In [173]:
for i in range(0,12):
    profit[i] = round(profit[i],2)

In [174]:
profit

[2522.67,
 1911.39,
 -3707.79,
 -2914.31,
 -599.92,
 7265.24,
 8210.55,
 3944.97,
 3328.39,
 -2238.65,
 659.6,
 11629.54]

In [175]:
# Profit after tax for each month
posttaxprofit = list(range(0,12))
for i in range(0,12):
    posttaxprofit[i] = profit[i]*0.7

In [176]:
for i in range(0,12):
    posttaxprofit[i] = round(posttaxprofit[i],2)

In [177]:
posttaxprofit

[1765.87,
 1337.97,
 -2595.45,
 -2040.02,
 -419.94,
 5085.67,
 5747.38,
 2761.48,
 2329.87,
 -1567.06,
 461.72,
 8140.68]

In [178]:
# Profit margin for each month - equals to the profit after tax divided by revenue
marginprofit = list(range(0,12))
for i in range(0,12):
    marginprofit[i] = posttaxprofit[i]/revenue[i]

In [179]:
marginprofit

[0.1211617010269313,
 0.17589916991609764,
 -0.3013966353942037,
 -0.2223355686557876,
 -0.05211046515235182,
 0.6274391026273712,
 0.49993389165886704,
 0.28276208800041774,
 0.22608419728839085,
 -0.10897526835957819,
 0.043095136536689956,
 0.527468169890174]

In [180]:
for i in range(0,12):
    marginprofit[i] = round(marginprofit[i]*100)

In [181]:
marginprofit

[12, 18, -30, -22, -5, 63, 50, 28, 23, -11, 4, 53]

In [182]:
type(marginprofit)

list

In [188]:
posttaxprofit = np.array(posttaxprofit)

In [189]:
posttaxprofit.mean()

1750.6808333333336

In [190]:
# Good Months
posttaxprofit

GoodMonths = []

for i in range(0,12):
    if posttaxprofit[i] > posttaxprofit.mean():
        GoodMonths.append(posttaxprofit[i])

In [191]:
GoodMonths

[1765.87, 5085.67, 5747.38, 2761.48, 2329.87, 8140.68]

In [200]:
# Good Months Boolean
GoodMonthList = list([])
for i in range(0,12):
    GoodMonthList.append(posttaxprofit[i] > posttaxprofit.mean())

In [201]:
GoodMonthList

[True, False, False, False, False, True, True, True, True, False, False, True]

In [192]:
# Bad Months

BadMonths = []

for i in range(0,12):
    if posttaxprofit[i] < posttaxprofit.mean():
        BadMonths.append(posttaxprofit[i])    

In [193]:
BadMonths

[1337.97, -2595.45, -2040.02, -419.94, -1567.06, 461.72]

In [202]:
# Bad Months Boolean
BadMonthList = list([])

for i in range(0,12):
    BadMonthList.append(posttaxprofit[i] < posttaxprofit.mean())

In [203]:
BadMonthList

[False, True, True, True, True, False, False, False, False, True, True, False]

In [194]:
# The Best Month
BestMonth = [max(posttaxprofit)]

In [197]:
BestMonth

[8140.68]

In [206]:
# The Best Month Boolean
BestMonthBoolean = list([])
for i in range(0,12):
    BestMonthBoolean.append(posttaxprofit[i] == posttaxprofit.max())

In [207]:
BestMonthBoolean

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True]

In [196]:
# The Worst Month
WorstMonth = [min(posttaxprofit)]

In [198]:
WorstMonth

[-2595.45]

In [208]:
# Worst Month Boolean
WorstMonthBoolean = list([])
for i in range(0,12):
    WorstMonthBoolean.append(posttaxprofit[i] == posttaxprofit.min())

In [209]:
WorstMonthBoolean

[False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]